version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: jobdb
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./job-back
    container_name: job-backend
    depends_on:
      - postgres
    ports:
      - "${BACKEND_PORT}:3001"
    environment:
      DATABASE_URL: ${DATABASE_URL}

  frontend:
    build: ./jobf
    container_name: job-frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    depends_on:
      - backend

volumes:
  pgdata:
